# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test4_1A.h
SOURCES += ./main.cpp \
    ./Test4_1A.cpp
FORMS += ./Test4_1A.ui
RESOURCES += Test4_1A.qrc
