# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test5_3A.h
SOURCES += ./main.cpp \
    ./Test5_3A.cpp
FORMS += ./Test5_3A.ui
RESOURCES += Test5_3A.qrc
