# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Test15_1A
DESTDIR = ../x64/Debug
QT += core opengl gui widgets concurrent
CONFIG += debug
DEFINES += WIN64 QT_DLL QT_WIDGETS_LIB QT_CONCURRENT_LIB QT_OPENGL_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/$(ConfigurationName)
LIBS += -lopengl32 \
    -lglu32
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Test15_1A.pri)
win32:RC_FILE = Test15_1A.rc
