# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test2_3A.h \
    ./MyWin.h
SOURCES += ./main.cpp \
    ./MyWin.cpp \
    ./Test2_3A.cpp
FORMS += ./Test2_3A.ui
RESOURCES += Test2_3A.qrc
