# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./GBK.hpp \
    ./Test10_2A.h
SOURCES += ./GBK.cpp \
    ./main.cpp \
    ./Test10_2A.cpp
FORMS += ./Test10_2A.ui
RESOURCES += Test10_2A.qrc
