# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test11_5A.h \
    ./MyWin.h
SOURCES += ./main.cpp \
    ./MyWin.cpp \
    ./Test11_5A.cpp
FORMS += ./Test11_5A.ui
RESOURCES += Test11_5A.qrc
