# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/Test7_3A.h \
    ./src/MyWin.h
SOURCES += ./src/main.cpp \
    ./src/MyWin.cpp \
    ./src/Test7_3A.cpp
FORMS += ./ui/MyWin.ui \
    ./ui/Test7_3A.ui
RESOURCES += Test7_3A.qrc
