# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test5_2A.h
SOURCES += ./main.cpp \
    ./Test5_2A.cpp
FORMS += ./Test5_2A.ui
RESOURCES += Test5_2A.qrc
