# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test12_6B.h
SOURCES += ./main.cpp \
    ./Test12_6B.cpp
FORMS += ./Test12_6B.ui
RESOURCES += Test12_6B.qrc
