# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test13_8A.h \
    ./CellWidget.h
SOURCES += ./CellWidget.cpp \
    ./main.cpp \
    ./Test13_8A.cpp
FORMS += ./CellWidget.ui \
    ./Test13_8A.ui
RESOURCES += Test13_8A.qrc
