# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test3_3B.h \
    ./MyWin.h
SOURCES += ./main.cpp \
    ./MyWin.cpp \
    ./Test3_3B.cpp
FORMS += ./MyWin.ui \
    ./Test3_3B.ui
RESOURCES += Test3_3B.qrc
