# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Test11_6A.h
SOURCES += ./main.cpp \
    ./Test11_6A.cpp
FORMS += ./Test11_6A.ui
RESOURCES += Test11_6A.qrc
